version: "3.9"

services:
  app:
    build: .
    container_name: myapp
    command: uvicorn src.main:app --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/postgres
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:15
    container_name: mydb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
