team:
   name: alfa-buena-maravilla-onda-dinamita-escruadron-lobo
   members:
      - user: af.donoso
        percentage: 25
      - user: d.corzos
        percentage: 25
      - user: gd.martinez
        percentage: 25
      - user: ne.cardenas
        percentage: 25
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/253/views/1
docs: <link al github pages del equipo>
users_app:
  folder: users_app
  image_name: users-app
  image_tag: 1.0.0
  authors:
    - ne.cardenas
posts_app:
  folder: posts_app
  image_name: <nombre de la imagen de la aplicación de publicaciones, mismo que el nombre en el archivo de despliegue de k8s>
  image_tag: <tag de la imagen de la aplicación de publicaciones, por ejemplo: latest, v1.0.0. Debe ser el mismo que el tag en el archivo de despliegue de k8s>
  authors:
    - gd.martinez
offers_app:
  folder: <nombre de la carpeta donde está la aplicación de ofertas>
  image_name: <nombre de la imagen de la aplicación de ofertas, mismo que el nombre en el archivo de despliegue de k8s>
  image_tag: <tag de la imagen de la aplicación de ofertas, por ejemplo: latest, v1.0.0. Debe ser el mismo que el tag en el archivo de despliegue de k8s>
  authors:
    - <usuario uniandes>
routes_app:
  folder: <nombre de la carpeta donde está la aplicación de trayectos>
  image_name: <nombre de la imagen de la aplicación de trayectos, mismo que el nombre en el archivo de despliegue de k8s>
  image_tag: <tag de la imagen de la aplicación de trayectos, por ejemplo: latest, v1.0.0. Debe ser el mismo que el tag en el archivo de despliegue de k8s>
  authors:
    - <usuario uniandes>
