---
# DB service
apiVersion: v1
kind: Service
metadata:
  name: dann-db-service
spec:
  type: ClusterIP
  selector:
    app: dann-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# DB deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dann-db-deployment
  labels:
    app: dann-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dann-db
  template:
    metadata:
      labels:
        app: dann-db
    spec:
      containers:
        - name: postgres-db
          image: postgres
          ports:
          - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: "danndb"
            - name: POSTGRES_PASSWORD
              value: "12345678"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: postgres-storage
          emptyDir:
            sizeLimit: 1Gi
