# Secret
apiVersion: v1
kind: Secret
metadata:
  name: rf005-app-secret
type: Opaque
stringData:
  POSTS_SERVICE_URL: "http://posts-app-service/posts"
  OFFERS_SERVICE_URL: "http://offers-app-service/offers"
  ROUTES_SERVICE_URL: "http://routes-app-service/routes"
  USERS_SERVICE_URL: "http://users-app-service/users"
  SCORES_SERVICE_URL: "http://scores-app-service/scores"

---
# App service
apiVersion: v1
kind: Service
metadata:
  name: rf005-service
spec:
  type: ClusterIP
  selector:
    app: rf005-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000

---
# App deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf005-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rf005-app
  template:
    metadata:
      labels:
        app: rf005-app
    spec:
      containers:
        - name: rf005-app
          image: 484569227865.dkr.ecr.us-east-1.amazonaws.com/rf005-app:2.0.0
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /rf005/ping
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          env:
            - name: POSTS_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: rf005-app-secret
                  key: POSTS_SERVICE_URL
            - name: OFFERS_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: rf005-app-secret
                  key: OFFERS_SERVICE_URL
            - name: ROUTES_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: rf005-app-secret
                  key: ROUTES_SERVICE_URL
            - name: USERS_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: rf005-app-secret
                  key: USERS_SERVICE_URL
            - name: SCORES_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: rf005-app-secret
                  key: SCORES_SERVICE_URL
