# ConfigMap
apiVersion: v1
kind: Secret
metadata:
  name: rf003-app-secret
type: Opaque
stringData:
  SERVER_URL: "0.0.0.0"
  SERVER_PORT: "3000"
  USERS_HOST: "http://users-app-service"
  ROUTES_HOST: "http://routes-app-service"
  POSTS_HOST: "http://posts-app-service"

---
# App service
apiVersion: v1
kind: Service
metadata:
  name: rf003-service
spec:
  type: ClusterIP
  selector:
    app: rf003-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
# App deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf003-app-deployment
  labels:
    app: rf003-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rf003-app
  template:
    metadata:
      labels:
        app: rf003-app
    spec:
      containers:
        - name: rf003-app
          # image: 381492016771.dkr.ecr.us-east-1.amazonaws.com/rf003:2.0.0
          image: rf003:3.0.0
          # imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
            - name: SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: rf003-app-secret
                  key: SERVER_URL
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: rf003-app-secret
                  key: SERVER_PORT
            - name: USERS_HOST
              valueFrom:
                secretKeyRef:
                  name: rf003-app-secret
                  key: USERS_HOST
            - name: ROUTES_HOST
              valueFrom:
                secretKeyRef:
                  name: rf003-app-secret
                  key: ROUTES_HOST
            - name: POSTS_HOST
              valueFrom:
                secretKeyRef:
                  name: rf003-app-secret
                  key: POSTS_HOST
            - name: GIN_MODE
              value: "release"
