# Secret
apiVersion: v1
kind: Secret
metadata:
  name: routes-app-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:12345678@terraform-20250914152707823100000001.c1wwg4wiavc5.us-east-1.rds.amazonaws.com:5432/danndb"

---
# App service
apiVersion: v1
kind: Service
metadata:
  name: routes-app-service
spec:
  type: ClusterIP
  selector:
    app: routes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000

---
# App deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routes-app-deployment
  labels:
    app: routes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routes-app
  template:
    metadata:
      labels:
        app: routes-app
    spec:
      containers:
        - name: routes-app
          image: 381492016771.dkr.ecr.us-east-1.amazonaws.com/routes_app:2.0.0
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /routes/ping
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: routes-app-secret
                  key: DATABASE_URL

# ---
# # DB service
# apiVersion: v1
# kind: Service
# metadata:
#   name: routes-db-service
# spec:
#   type: ClusterIP
#   selector:
#     app: routes-db
#   ports:
#     - protocol: TCP
#       port: 5432
#       targetPort: 5432

# ---
# # DB deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: routes-db-deployment
#   labels:
#     app: routes-db
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: routes-db
#   template:
#     metadata:
#       labels:
#         app: routes-db
#     spec:
#       containers:
#         - name: postgres-db
#           image: postgres
#           ports:
#             - containerPort: 5432
#           volumeMounts:
#             - name: routes-db-volume
#               mountPath: /var/lib/postgresql/data
#           env:
#             - name: POSTGRES_DB
#               valueFrom:
#                 secretKeyRef:
#                   name: routes-app-config
#                   key: DB_NAME
#             - name: POSTGRES_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: routes-app-config
#                   key: DB_PASSWORD
#           livenessProbe:
#             exec:
#               command:
#                 - pg_isready
#                 - -U
#                 - postgres
#             initialDelaySeconds: 30
#             periodSeconds: 10
#             timeoutSeconds: 5
#             failureThreshold: 5
#           readinessProbe:
#             exec:
#               command:
#                 - pg_isready
#                 - -U
#                 - postgres
#             initialDelaySeconds: 5
#             periodSeconds: 5
#             timeoutSeconds: 3
#             failureThreshold: 3
#       volumes:
#         - name: routes-db-volume
#           emptyDir:
#             sizeLimit: 1Gi

# ---
# # Allow routes-app to DB Network Policy
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: routes-network
# spec:
#   podSelector:
#     matchLabels:
#       app: routes-db
#   policyTypes:
#     - Ingress
#   ingress:
#     - from:
#         - podSelector:
#             matchLabels:
#               app: routes-app
#       ports:
#         - protocol: TCP
#           port: 5432
