@startuml components
skinparam componentStyle rectangle

actor User

component "TrueNative" as TrueNative

frame "env" {

    component "Ingress" as ingress

    component "users_app" as usersApp

    component "credit_cards_app" as creditCardsApp

    component "consumer" as consumer
    
    component "SQS" as sqs

    component "notification" as notificationApp

    User ..> ingress

    ' Conexiones usuario -> apps
    ingress ..> usersApp
    ingress ..> creditCardsApp

    consumer --> creditCardsApp
    creditCardsApp --> usersApp

    creditCardsApp --> notificationApp
    usersApp --> notificationApp

    consumer --> sqs
    creditCardsApp --> sqs

    ' Conexiones apps -> bases de datos
    database "db" as db
    usersApp --> db
    creditCardsApp --> db
}

usersApp ..> TrueNative
creditCardsApp ..> TrueNative

@enduml
