@startuml deployment
!define DOCKER ./docs/icons/docker.png

person "User" as user

frame "k8s" {

  
   component "Ingress" as ingress
   
  user ..> ingress : "HTTP"

   component "users-app-service" as usersAppService
   component "posts-app-service" as postsAppService
   component "offers-app-service" as offersAppService
   component "routes-app-service" as routesAppService
   component "scores-app-service" as scoresAppService
   component "rf003-service" as rf003Service
   component "rf004-service" as rf004Service
   component "rf005-service" as rf005Service

  ingress --> usersAppService : "HTTP"
  ingress --> postsAppService : "HTTP"
  ingress --> offersAppService : "HTTP"
  ingress --> routesAppService : "HTTP"
  ingress --> scoresAppService : "HTTP"
  ingress --> rf003Service : "HTTP"
  ingress --> rf004Service : "HTTP"
  ingress --> rf005Service : "HTTP"

  rf003Service ..> usersAppService : "HTTP"
  rf003Service ..> postsAppService : "HTTP"
  rf003Service ..> routesAppService : "HTTP"

  rf004Service ..> usersAppService : "HTTP"
  rf004Service ..> postsAppService : "HTTP"
  rf004Service ..> routesAppService : "HTTP"
  rf004Service ..> offersAppService : "HTTP"
  rf004Service ..> scoresAppService : "HTTP"

  rf005Service ..> usersAppService : "HTTP"
  rf005Service ..> postsAppService : "HTTP"
  rf005Service ..> routesAppService : "HTTP"
  rf005Service ..> offersAppService : "HTTP"
  rf005Service ..> scoresAppService : "HTTP"

  frame "pod" as usersAppPod {
    frame "users-app" {
      frame "<img:DOCKER{scale=0.5}>" as usersAppDocker {
        component "users_app" as usersAppComponent
      }
    }
  }

  frame "pod" as postsAppPod {
    frame "posts-app" {
      frame "<img:DOCKER{scale=0.5}>" as postsAppDocker {
        component "posts_app" as postsAppComponent
      }
    }
  }

  frame "pod" as offersAppPod {
    frame "offers-app" {
      frame "<img:DOCKER{scale=0.5}>" as offersAppDocker {
        component "offers_app" as offersAppComponent
      }
    }
  }

  frame "pod" as routesAppPod {
    frame "routes-app" {
      frame "<img:DOCKER{scale=0.5}>" as routesAppDocker {
        component "routes_app" as routesAppComponent
      }
    }
  }

  frame "pod" as scoresAppPod {
    frame "scores-app" {
      frame "<img:DOCKER{scale=0.5}>" as scoresAppDocker {
        component "scores_app" as scoresAppComponent
      }
    }
  }

  usersAppService --> usersAppComponent
  postsAppService --> postsAppComponent
  offersAppService --> offersAppComponent
  routesAppService --> routesAppComponent
  scoresAppService --> scoresAppComponent

  database "db" as dbComponent
  
  usersAppComponent --> dbComponent
  postsAppComponent --> dbComponent
  offersAppComponent --> dbComponent
  routesAppComponent --> dbComponent

  artifact "db-volumen" as dbVolume

  dbComponent --> dbVolume
}
@enduml
