@startuml deployment
!define DOCKER ./docs/icons/docker.png

person "User" as user

frame "AWS lambda & SQS" {
  component "SQS" as sqsComponent

  frame "<img:DOCKER{scale=0.5}>" as consumerDocker {
    component "consumer" as consumerComponent
  }

  consumerComponent --> sqsComponent : "Consume messages"
}

component "TrueNative" as TrueNative

frame "k8s" {
   component "Ingress" as ingress
   
  user ..> ingress : "HTTP"

   component "users-app-service" as usersAppService
   component "credit-cards-app-service" as creditCardsAppService
   component "notification-app-service" as notificationAppService

  ingress --> usersAppService : "HTTP"
  ingress --> creditCardsAppService : "HTTP"
  ingress --> notificationAppService : "HTTP"

  frame "pod" as usersAppPod {
    frame "users-app" {
      frame "<img:DOCKER{scale=0.5}>" as usersAppDocker {
        component "users_app" as usersAppComponent
      }
    }
  }

  frame "pod" as creditCardsAppPod {
    frame "credit-cards-app" {
      frame "<img:DOCKER{scale=0.5}>" as creditCardsAppDocker {
        component "credit_cards_app" as creditCardsAppComponent
      }
    }
  }

  frame "pod" as notificationAppPod {
    frame "notification-app" {
      frame "<img:DOCKER{scale=0.5}>" as notificationAppDocker {
        component "notification_app" as notificationAppComponent
      }
    }
  }

  usersAppService --> usersAppComponent
  creditCardsAppService --> creditCardsAppComponent
  notificationAppService --> notificationAppComponent

  database "db" as dbComponent
  
  usersAppComponent --> dbComponent
  creditCardsAppComponent --> dbComponent

  artifact "db-volumen" as dbVolume

  dbComponent --> dbVolume
}

creditCardsAppComponent ..> TrueNative : "HTTP"
usersAppComponent ..> TrueNative : "HTTP"

@enduml
