@startuml

skinparam linetype polyline
skinparam linetype ortho

entity "users" as users {
    * id : uuid
    --
    * username : varchar(255)
    * email : varchar(255)
    phoneNumber : varchar(255)
    dni : varchar(255)
    fullName : varchar(255)
    * password : varchar(255)
    * salt : varchar(255)
    * token : varchar(255)
    * status : varchar(50) <<POR_VERIFICAR | NO_VERIFICADO | VERIFICADO>>
    * expireAt : timestamptz
    * createdAt : timestamptz
    * updatedAt : timestamptz
}

entity "routes" as routes {
    * id : uuid
    --
    * flightId : varchar(255)
    * sourceAirportCode : varchar(10)
    * sourceCountry : varchar(255)
    * destinyAirportCode : varchar(10)
    * destinyCountry : varchar(255)
    * bagCost : int
    * plannedStartDate : timestamptz
    * plannedEndDate : timestamptz
    * createdAt : timestamptz
    * updatedAt : timestamptz
}

entity "posts" as posts {
    * id : uuid
    --
    * routeId : uuid
    * userId : uuid
    * expireAt : timestamptz
    * createdAt : timestamptz
}

entity "offers" as offers {
    * id : uuid
    --
    * postId : uuid
    * userId : uuid
    * description : varchar(140)
    * size : varchar(20) <<LARGE | MEDIUM | SMALL>>
    * fragile : boolean
    * offer : numeric
    * createdAt : timestamptz
}

' ==== RELACIONES ====
users ||--o{ posts
posts ||--|| routes
posts ||--o{ offers

@enduml
