@startuml

skinparam linetype polyline
skinparam linetype ortho

entity "users" as users {
    * id : uuid
    --
    * username : varchar(255)
    * email : varchar(255)
    * phoneNumber : varchar(255)
    * dni : varchar(255)
    * fullName : varchar(255)
    * password : varchar(255)
    * salt : varchar(255)
    * token : varchar(255)
    * status : varchar(50) <<POR_VERIFICAR | NO_VERIFICADO | VERIFICADO>>
    * expireAt : timestamptz
    * createdAt : timestamptz
    * updatedAt : timestamptz
}

entity "creditCard" as creditCards {
    * id : uuid
    --
    * token : varchar(255)
    * userId : uuid
    * lastFourDigits : varchar(4)
    * ruv : varchar(255)
    * issuer: varchar(255) <<VISA | MASTERCARD | AMERICAN EXPRESS | DISCOVER | DINERS CLUB | UNKNOWN>>
    * status: varchar(50) <<POR_VERIFICAR | RECHAZADA | APROBADA>>
    * updatedAt : timestamptz
    * createdAt : timestamptz
}

' ==== RELACIONES ====
users ||--o{ creditCards

@enduml
