@startuml
skinparam shadowing false
skinparam rectangle {
    BackgroundColor White
    BorderColor Black
}
skinparam cloud {
    BackgroundColor #fff8dc
    BorderColor Black
}
skinparam frame {
    BackgroundColor White
    BorderColor Black
}
skinparam component {
    BackgroundColor White
    BorderColor Black
}

cloud "Internet" as internet

frame "K8s" {
    frame "Node" {
        ' INTERNET -> NODE PORTS
        internet ..> n1 : Port: 30000
        internet ..> n2 : Port: 30001
        internet ..> n3 : Port: 30002
        internet ..> n4 : Port: 30003

        ' USERS NETWORK
        frame "users-network" #Green {
            component "users-app-service" <<Port: 80>> as usersAppService
            
            component "users-app" <<Port: xxxx>> as usersAppPod {
              component "users_app" as usersApp
            }
            component "users-db-service" <<Port: 5432>> as usersDbService
            component "users-db" <<Port: 5432>> as usersDbPod {
                component "users_db" as usersDb
            }

            n1 --> usersAppService
            usersAppService --> usersAppPod
            usersApp --> usersDbService
            usersDbService --> usersDbPod
        }

        ' POSTS NETWORK
        frame "posts-network" #Green {
            component "posts-app-service" <<Port: 80>> as postsAppService
            component "posts-app" <<Port: xxxx>> as postsAppPod {
                component "posts_app" as postsApp
            }
            component "posts-db-service" <<Port: 5432>> as postsDbService
            component "posts-db" <<Port: 5432>> as postsDbPod {
                component "posts_db" as postsDb
            }

            n2 --> postsAppService
            postsAppService --> postsAppPod
            postsApp --> postsDbService
            postsDbService --> postsDbPod
        }

        ' ROUTES NETWORK
        frame "routes-network" #Green {
            component "routes-app-service" <<Port: 80>> as routesAppService
            component "routes-app" <<Port: xxxx>> as routesAppPod {
                component "routes_app" as routesApp
            }
            component "routes-db-service" <<Port: 5432>> as routesDbService
            component "routes-db" <<Port: 5432>> as routesDbPod {
                component "routes_db" as routesDb
            }

            n3 --> routesAppService
            routesAppService --> routesAppPod
            routesApp --> routesDbService
            routesDbService --> routesDbPod
        }

        ' OFFERS NETWORK
        frame "offers-network" #Green {
            component "offers-app-service" <<Port: 80>> as offersAppService
            component "offers-app" <<Port: xxxx>> as offersAppPod {
                component "offers_app" as offersApp
            }
            component "offers-db-service" <<Port: 5432>> as offersDbService
            component "offers-db" <<Port: 5432>> as offersDbPod {
                component "offers_db" as offersDb
            }

            n4 --> offersAppService
            offersAppService --> offersAppPod
            offersApp --> offersDbService
            offersDbService --> offersDbPod
        }
    }
}
@enduml