name: Evaluador Pruebas Unitarias
# Actualice este pipeline si usted decide trabajar en una tecnología diferente a Python.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify-app:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [users_app, offers_app, posts_app, routes_app]
    steps:
      - uses: actions/checkout@v4

      - name: Check if folder exists
        id: check_folder
        run: |
          if [ -d "${{ matrix.app }}" ]; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Stop if folder missing
        if: env.exists == 'false'
        run: |
          echo "Skipping because folder '${{ matrix.app }}' does not exist."
          exit 0

      - name: Set up Python
        if: env.exists == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set up Poetry
        if: env.exists == 'true'
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.1

      - name: Run linter checkers in ${{ matrix.app }}
        if: env.exists == 'true'
        run: make lintcheck DIR=${{ matrix.app }}

      - name: Run unit tests in ${{ matrix.app }}
        if: env.exists == 'true'
        run: make unittest DIR=${{ matrix.app }}
